### ISSUE TITLE
Cannot import partials from outside /styles

### ISSUE THREAD

**Issue by mydea** [aexmachina/ember-cli-sass#76] opened 2015-09-21 09:04 UTC
In my app, I have _style.scss partials in my pods, which I simply import in my app.scss.

This used to work well, but since last week I get the following error message when trying to serve or build:

```
File: C:/projects/ember-cli-example-app-for-github/tmp/sass_compiler-input_base_path-vJ52cHSX.tmp/0/app/styles/app.scss (1)
file to import not found or unreadable: ./../test
Current dir: C:/projects/ember-cli-example-app-for-github/tmp/sass_compiler-input_base_path-vJ52cHSX.tmp/0/app/styles/
Error: file to import not found or unreadable: ./../test
Current dir: C:/projects/ember-cli-example-app-for-github/tmp/sass_compiler-input_base_path-vJ52cHSX.tmp/0/app/styles/
    at options.error (C:\projects\ember-cli-example-app-for-github\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\lib\index.js:277:32)
```

```scss
// app/styles/app.scss

@import "./../test";
```

```scss
// app/_test.scss

body {}
```

```js
// ember-cli-build.js

var app = new EmberApp(defaults, {
  sassOptions: {
    includePaths: [
      'app'
    ]
  }
});
```

My setup:

- Windows 10
- Node 4.0
- ember-cli 1.13.8
- ember-cli-sass 4.2.0

The problem also occurs on OS X. The problem started on multiple machines after clearing the node_modules folder and reinstalling with npm install. Another machine, which did not clear the node_modules folder, continues working, even when running `npm install`.

I made a minimal repo which shows the issue: https://github.com/mydea/ember-cli-example-app-for-github/tree/ember-cli-sass

I get the error on multiple machines. I ran `bower cache clean` and `npm cache clean`, then installed all dependencies with `npm install && bower install`.

**Comment by aexmachina** [comment] 2015-09-23 06:12
Closing as a duplicate of #73.

**Closed by aexmachina** 2015-09-23 06:12 UTC
