### ISSUE TITLE
css not rebuild if sass file is not in styles folder

### ISSUE THREAD

**Issue by pogopaule** [aexmachina/ember-cli-sass#73] opened 2015-09-14 15:07 UTC
I put style files related to a component into [the component's pod folder](https://github.com/pogopaule/sass-bug/blob/master/app/components/foo-bar/_style.scss)

Changing the component's style used to trigger a rebuild of the css, even with ember-cli 1.13.8...now suddenly it does not anymore...why?

To reproduce:
1. check out https://github.com/pogopaule/sass-bug
2. run `ember serve`
3. change [the components style file](https://github.com/pogopaule/sass-bug/blob/master/app/components/foo-bar/_style.scss)
4. take a look at ember-cli's output. The change should trigger a rebuild. `file changed components/foo-bar/_style.scss`
5. take a look at the website...the change has not been reflected. The css has not been rebuild.
6. It takes a a restart of the server to rebuild the css :cry:  

This might be related to #69

**Comment by pogopaule** [comment] 2015-09-14 15:09
https://github.com/DudaDev/ember-cli-sass-pods/issues/8 might be related as well?

**Comment by pogopaule** [comment] 2015-09-14 15:47
just figured out that the issue does not occur with ember-cli 1.13.1 but does starting with 1.13.5

**Comment by Orgil** [comment] 2015-09-15 04:34
I'm also having exact problem.

**Comment by aexmachina** [comment] 2015-09-15 10:24
Problem looks to be an ember-cli regression to me. See the above issue for more info.

**Comment by aexmachina** [comment] 2015-09-23 06:13
Workaround until the issue is fixed in ember-cli is likely to be using ember-cli version less than 1.13.5

**Comment by munsellj** [comment] 2015-11-21 01:45
In case anyone else is suffering from this issue and finds this in the future, here's the corresponding issue in ember-cli that you can subscribe to for updates:  https://github.com/ember-cli/ember-cli/issues/4658

**Comment by sglanzer** [comment] 2016-01-11 02:56
I commented on the linked ember-cli issue, but it appears to be piggybacking on another issue report.  Has anyone found a solution to this problem or is it something that needs to be promoted in ember-cli issues?

**Comment by kylenathan** [comment] 2016-01-12 17:23
Have opened a separate issue for this: https://github.com/ember-cli/ember-cli/issues/5333

**Comment by aexmachina** [comment] 2016-04-11 23:48
Closing due to inactivity, feel free to reopen.

**Closed by aexmachina** 2016-04-11 23:48 UTC

**Comment by munsellj** [comment] 2017-02-16 14:50
FYI for anyone visiting this in the future. We were able to solve this by adding the `app` directory that our pods styles were under to the included paths in sass options.

Add paths for watching in the 'ember.cli-build.js':
```
var app = new EmberApp(defaults, {
  sassOptions: {
    includePaths: ['app']
  }
});
```

**Comment by tschoartschi** [comment] 2019-03-22 12:55
Just tried it with the following setup:

```
ember-cli: 3.7.1
ember-cli-sass: 10.0.0
sass: 1.17.3
node: 10.13.0
os: darwin x64
```
The problem is, that I can not import anything inside the file which is in the `app` directory. Not sure who is messing around with the paths but it's very weird. I created a repo which demonstrates the issue:

https://github.com/tschoartschi/ember-cli-sass-import-troubles

In the [following file](https://github.com/tschoartschi/ember-cli-sass-import-troubles/blob/master/app/components/break-import/_style.scss) I added comments to demonstrate what works and what not
