### ISSUE TITLE
Sass Syntax Error (SassCompiler) Error: Can't find stylesheet to import

### ISSUE THREAD

**Issue by pusle** [aexmachina/ember-cli-sass#194] opened 2018-09-07 07:26 UTC
I have just updated my Ember app from 2.18 to 3.4. All deprecations are fixed. I use a few addons as can be seen in this gist: https://gist.github.com/pusle/a7298a58f33074a462a72c722c158c15

After updating I noticed that _ember-cli-sass_ did not work, and no CSS was built. Most noticable the tailwind CSS from _ember-cli-tailwind_ was missing. I tried to remove _ember-cli-sass_ and _ember-cli-tailwind_ (and also _ember-power-select_, cant remember why). 

Then I completely cleared the npm cache, deleted _tmp_, _dist_ and _node_modules_ folders, checked the _package.json_ to see that the addons was gone. I ran `npm install` after renaming _app.scss_ to _app.css_ and it seemed to work. 

Now I began to re-add addons. First _ember-cli-tailwind_. That worked fine. Then _ember-cli-sass_. Now when I run `ember s`, I get a Sass Syntaxt Error:

Sass Syntax Error (SassCompiler) in /tailstorm/styles/app.scss:1:9

```
Error: Can't find stylesheet to import.
@import "ember-power-select";
        ^^^^^^^^^^^^^^^^^^^^
  tmp/sass_compiler-input_base_path-6cc1OO2p.tmp/tailstorm/styles/app.scss 1:9  root stylesheet


Stack Trace and Error Report: /var/folders/3b/1b2trz197vx3lwhccn2pnv2c0000gn/T/error.dump.3e678fb6c207f5fe61b3219cb4618a16.log
```

See error.dump in this gist: https://gist.github.com/pusle/a53412354a69f77721698d9a78096e07

I have searched the complete project for ember-power-select, but can not find any occurrences. Also, the _app.scss_ does not import anything other than tailwind.

Please let me know if I should provide more information.

Thanks.

**Comment by pusle** [comment] 2018-09-07 11:20
After editing  _tmp/sass_compiler-input_base_path-6cc1OO2p.tmp/tailstorm/styles/app.scss_ and removing the line `@import "ember-power-select"` it works. For some reason I had the impression that deleting the entire _tmp_ folder would remove any reference to _ember-power-select_ after removing the addon from _package.json_, deleting _package-lock.json_ and deleting _node_modules_ folder. 

What I don't understand is how `@import "ember-power-select";` is added to the sass_compiler-input_base_path after doing the above steps.

**Comment by tniezurawski** [comment] 2019-08-13 11:43
@pusle It seems like your problem was with a cache or something like that?

I'm trying to go from version `7.1.4` to `8.0.1` (and to `10.0.1` eventually) but I get the error you've mentioned:
```
Error: Can't find stylesheet to import.
@import "ember-power-select";
        ^^^^^^^^^^^^^^^^^^^^
```

it seems like resolving the path to addon's style is broken since 8.0.1. Maybe I'll try to reproduce it with a fresh project that has only `ember-power-select`'s style imported 🤷‍♂ 

----

Is any `@import` working for you in your project?

**Comment by pusle** [comment] 2019-08-19 07:02
Yes they are. 

I started this project from scratch and everything worked fine. It has been a while now, so can't remember the details.

**Closed** 2019-08-23 18:58 UTC
