### ISSUE TITLE
v7.1.4 introduces a syntax error for block-scoped declarations when running under node 4

### ISSUE THREAD

**Issue by ethanherbertson** [aexmachina/ember-cli-sass#180] opened 2018-01-19 15:37 UTC
I'm getting syntax errors when I run `ember test` under node 4.8.4:

```
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.Addon.lookup (... etc. etc. etc. ...)
```

The only difference between a clone that is still working and the one that has started failing is that the failing one has ember-cli-sass@7.1.4 installed, while the working one has 7.1.3.

Spelunking a bit shows this to be the only functional difference:

```diff
--- 7.1.3/index.js  2017-12-27 15:04:33.000000000 -0600
+++ 7.1.4/index.js  2018-01-18 05:53:18.000000000 -0600
@@ -1,7 +1,7 @@
 /* eslint-env node */
 var SassCompiler = require('broccoli-sass-source-maps');
 var path = require('path');
-var checker = require('ember-cli-version-checker');
+var VersionChecker = require('ember-cli-version-checker');
 var Funnel = require('broccoli-funnel');
 var mergeTrees = require('broccoli-merge-trees');
 var fs = require('fs');
@@ -45,7 +45,8 @@
   name:  'ember-cli-sass',

   shouldSetupRegistryInIncluded: function() {
-    return !checker.isAbove(this, '0.2.0');
+    let checker = new VersionChecker(this);
+    return !checker.for('ember-cli').isAbove('0.2.0');
   },

   sassOptions: function () {
```

That `let checker` declaration is almost certainly the issue.

**Comment by jacobq** [comment] 2018-01-24 20:50
I encounter the same problem when attempting to upgrade from v6.2.0 to v7.0.0, so I don't think it's just v7.1.4 where the problem is introduced.

**Comment by jacobq** [comment] 2018-01-24 21:12
It looks like `"use strict";` was added to `index.js` just recently ([commit `fb2595f`](https://github.com/aexmachina/ember-cli-sass/commit/fb2595ff5bce1010c0fee472f389ffbfe7689c04))
so try `"ember-cli-sass": "git+ssh://git@github.com/aexmachina/ember-cli-sass#master"`. This resolves the problem for me.

**Comment by ethanherbertson** [comment] 2018-01-24 22:42
@jacobq Locking down dependencies to a specific commit like that is often an anti-pattern, because it costs you the benefits of [semantic versioning](https://semver.org/). And, depending on the maintainer, unreleased commits on GitHub may be untested.

But it's good to know it has been fixed in a future commit, at least!

**Comment by jacobq** [comment] 2018-01-24 22:47
@ethanherbertson Yes, I understand that. You would want to use the next release once it is available. I just suggested trying that (sometimes I use `#master` but that's even wilder) to confirm that it indeed solves your problem. If so, you can close the issue and make a reminder to upgrade next month or whenever the next release ships.

**Comment by Exelord** [comment] 2018-02-04 21:23
This is a very serious issue as it stops builds and even usage of any ember-cli under npm@4.
Can we speed up somehow the fix release?

**Comment by jacobq** [comment] 2018-02-04 22:43
@Exelord, can you set your dependencies to use 7.1.3 (e.g. instead of ^7.1.0 --> 7.1.4) to work around this or is the problem coming from another package? (e.g. try`npm ls ember-cli-sass@7.1.4`)

**Comment by Exelord** [comment] 2018-02-04 23:00
That's how I did it, for know. But for many users it can be a huge problem during upgrades as the error doesn't specify the broken addon.

**Comment by ouarez** [comment] 2018-02-07 01:54
I've encountered the same issue. It drove me temporarily insane as I couldn't figure out why ember-cli had just stopped working for no obvious reason :)

I can confirm that specifying `"ember-cli-sass": "aexmachina/ember-cli-sass#fb2595ff5bce1010c0fee472f389ffbfe7689c04"` inside `package.json` fixed the issue for me.

**Comment by Exelord** [comment] 2018-02-07 09:56
That's what I was saying. We should fix it immediately, as soon as possible. It's breaking users builds especially if they are using `~7.1.0`- they even didn't make this upgrade intentionally so they notice that.

**Comment by Turbo87** [comment] 2018-02-15 16:09
@aexmachina would it be possible to release a v7.1.5 from the current `master`? I think that should fix this issue.

**Comment by aexmachina** [comment] 2018-02-15 23:07
Okay, that's done. Sorry that took a while.

**Closed by aexmachina** 2018-02-15 23:07 UTC

**Comment by Turbo87** [comment] 2018-02-15 23:09
Thanks! ❤️
