### ISSUE TITLE
Segmentation fault with no error message

### ISSUE THREAD

**Issue by dehrax** [aexmachina/ember-cli-sass#117] opened 2016-04-07 13:57 UTC
I tried to serve my application, but it wouldn't start. After a bit of work we figured out it was a stylesheet. After a bit more work we realized it was regular mistake:

```sass
.rating
    display: flex
        width: 100px
            .material-icons
                max-width: 20px
```

The obvious mistake is the .material-icons is displaced. I did not get an error message saying that, only (on OSx) segmentation fault.

I am running Windows 10.

Screenshot Windows
![pasted image at 2016_04_07 02_36 pm](https://cloud.githubusercontent.com/assets/1438972/14353390/24201f5c-fcd9-11e5-88f3-b468b81a6e7c.png)

Screenshot OSx
<img width="627" alt="skarmavbild 2016-04-07 kl 15 56 04" src="https://cloud.githubusercontent.com/assets/1438972/14353440/607781a2-fcd9-11e5-958e-d6019d4e7117.png">

**Comment by aexmachina** [comment] 2016-04-07 23:59
This is a node-sass issue. This module is a thin wrapper around node-sass. You're welcome to post this issue on the node-sass issue tracker.

**Comment by mike-north** [comment] 2016-04-22 11:31
While it's true that the issue doesn't lie within this library, we still should assume responsibility for creating a good experience for consumers whenever possible. The issue here has to do with the version of `libsass` that `node-sass v3.5.x` pulls in. I've opened up [an issue in broccoli-sass-source-maps](https://github.com/aexmachina/broccoli-sass-source-maps/issues/19) with a proposed solution. Hope we can get a fix for this soon, as I have had to help dozens of people get past this while teaching workshops.

**Comment by aexmachina** [comment] 2016-04-22 11:58
There's a workaround [here](https://github.com/aexmachina/broccoli-sass-source-maps#usage). I should add this to the README but I'm not at the computer.

**Comment by aexmachina** [comment] 2016-04-26 01:55
I've added docs for the workaround to ember-cli-sass.

**Comment by dustinfarris** [comment] 2016-07-27 13:51
This appears to have been fixed in [libsass 3.3.6](https://github.com/sass/libsass/releases/tag/3.3.6).  Recent versions of node-sass  are using this latest libsass, so we should be able to simply upgrade the node-sass version and this issue will go away.

**Comment by dustinfarris** [comment] 2016-07-27 13:57
Created upstream PR https://github.com/aexmachina/broccoli-sass-source-maps/pull/20

**Comment by mike-north** [comment] 2016-07-27 13:59
Would love to see a fix here. Part of the problem is that ember-cli 2.5 doesn't treat `ember-cli-build.js` properly in blueprints, so there's no way to set a working version of node-sass up for users automatically.

**Comment by aexmachina** [comment] 2016-07-28 01:22
Published v5.4.0 which upgrades node-sass

**Closed by aexmachina** 2016-07-28 01:22 UTC

**Comment by jaider2523** [comment] 2016-08-22 16:25
Hi,

I have the same problem, what is the explicit solution?....I'm use ember cli..... 

This my devdependencies:

  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.7.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-materialize": "0.22.0-beta.0",
    "ember-cli-qunit": "^2.0.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "^5.5.1",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-composability": "0.3.7",
    "ember-data": "^2.7.0",
    "ember-export-application-global": "^1.0.5",
    "ember-keyboard": "1.0.3",
    "ember-load-initializers": "^0.5.1",
    "ember-material-design-icons-shim": "0.1.9",
    "ember-materialize-shim": "0.2.3",
    "ember-modal-dialog": "0.8.8",
    "ember-new-computed": "1.0.3",
    "ember-radio-button": "1.0.7",
    "ember-resolver": "^2.0.3",
    "ember-truth-helpers": "1.2.0",
    "ember-welcome-page": "^1.0.1",
    "loader.js": "^4.0.1",
    "node-sass": "3.4.2"
  },

![captura de pantalla 2016-08-22 a la s 11 23 24 a m](https://cloud.githubusercontent.com/assets/5841349/17862459/eb37df98-685a-11e6-907e-e7d7c2569565.png)

Thanks!

**Comment by dustinfarris** [comment] 2016-08-22 16:26
@jaider2523 you can get rid of the explicit node-sass dependency now.

**Comment by jaider2523** [comment] 2016-08-22 16:40
@dustinfarris  Oh Man.... Thanks......work fine....
