### ISSUE TITLE
sassOptions is ignored in production build

### ISSUE THREAD

**Issue by barneycarroll** [aexmachina/ember-cli-sass#116] opened 2016-04-06 12:00 UTC
I want to ensure SASS builds with an `outputStyle` of `'compact'` [1].

However running a production build seems to ignore this app config [2]. Any ideas?

[1] SASS's `'compressed'` mode deems unit suffixes for 0 values to be redundant, but IE11 has a flexbox implementation bug that disagrees.

[2] My `ember-cli-build.js`:

```javascript
/*jshint node:true*/
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    sassOptions : {
      outputStyle : 'compact'
    }
  });  

  return app.toTree();
```

**Comment by aexmachina** [comment] 2016-04-07 01:49
The `outputStyle` option is passed straight through to node-sass, without modification. The environment (development/production) has no effect on this. Maybe the issue is with node-sass?

**Comment by barneycarroll** [comment] 2016-04-07 05:56
Thanks for your prompt response! node-sass could be the culprit. Do you have any tips on how to debug Ember CLI subprocesses? I wouldn't even know how to assert that.

The reason I assume Ember CLI Sass is doing something under the hood is that the output style *is* respected when I build for an environment other than production. When I run a production build, the output CSS output is always the same and resembles `compressed`. Perhaps an unrelated vanilla Ember CLI post build process is taking place to compress output?

**Comment by aexmachina** [comment] 2016-04-07 23:11
Yes, I'd say that it's another addon, or maybe ember-cli has a default minifier for production. Are there any other addons that could be touching your CSS e.g. an autoprefixer?

Debugging is the same as any other node module: just open up the files in `node_modules/` and add console log statements \o/ The options are passed to node-sass in the call to `this.renderSass` on line 66 of `broccoli-sass-source-maps/index.js`.

**Comment by aexmachina** [comment] 2016-04-11 23:44
Closing this issue, but feel free to reopen if you think this is indeed an issue with ember-cli-sass.

**Closed by aexmachina** 2016-04-11 23:44 UTC

**Comment by barneycarroll** [comment] 2016-04-12 08:35
Thanks for the tips Simon — I'll post back here when I find a solution for any others who stumble on this.

**Comment by runspired** [comment] 2022-05-06 06:14
I think this is related to #231 and as I dive deeper I'm starting to think ember-cli does something out-of-the-box to set sass options as this addon does not set `outputStyle` nor do any of the other addons/apps I'm working on at the moment.
